name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Kodni olish
        uses: actions/checkout@v3

      - name: Docker image build
        run: docker build -t my-app:latest .

      - name: Eskisini toxtatish
        run: |
          docker stop my-app
          docker rm my-app
        shell: pwsh
        continue-on-error: true

      - name: Yangi konteynerni ishga tushirish
        run: |
          docker run -d --name my-app -p 3000:3000 my-app:latest